In [0]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import tensorflow as tf

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
data = '/content/around the world in eighty days.txt' #https://www.gutenberg.org/ebooks/103

In [0]:
text = open(data,'r',encoding='utf-8').read()

In [0]:
vocab = sorted(set(text))

In [9]:
len(vocab)

78

In [10]:
char_to_ind = {char:i for i,char in enumerate(vocab)}
print(char_to_ind)

{'\n': 0, ' ': 1, '!': 2, '"': 3, '&': 4, "'": 5, '(': 6, ')': 7, '+': 8, ',': 9, '-': 10, '.': 11, '0': 12, '1': 13, '2': 14, '3': 15, '4': 16, '5': 17, '6': 18, '7': 19, '8': 20, '9': 21, ':': 22, ';': 23, '?': 24, 'A': 25, 'B': 26, 'C': 27, 'D': 28, 'E': 29, 'F': 30, 'G': 31, 'H': 32, 'I': 33, 'J': 34, 'K': 35, 'L': 36, 'M': 37, 'N': 38, 'O': 39, 'P': 40, 'Q': 41, 'R': 42, 'S': 43, 'T': 44, 'U': 45, 'V': 46, 'W': 47, 'X': 48, 'Y': 49, 'Z': 50, '`': 51, 'a': 52, 'b': 53, 'c': 54, 'd': 55, 'e': 56, 'f': 57, 'g': 58, 'h': 59, 'i': 60, 'j': 61, 'k': 62, 'l': 63, 'm': 64, 'n': 65, 'o': 66, 'p': 67, 'q': 68, 'r': 69, 's': 70, 't': 71, 'u': 72, 'v': 73, 'w': 74, 'x': 75, 'y': 76, 'z': 77}


In [0]:
ind_to_char = np.array(vocab)

In [12]:
ind_to_char[56] 

'e'

In [13]:
char_to_ind['e']

56

In [0]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [54]:
print(encoded_text)
print(encoded_text.shape)

[27 59 52 ... 63 55 24]
(367444,)


In [16]:
sample = text[101:202]
print(sample)

MAN


Mr. Phileas Fogg lived, in 1872, at No. 7, Saville Row, Burlington
Gardens, the house in which 


In [17]:
encoded_text[101:202]

array([37, 25, 38,  0,  0,  0, 37, 69, 11,  1, 40, 59, 60, 63, 56, 52, 70,
        1, 30, 66, 58, 58,  1, 63, 60, 73, 56, 55,  9,  1, 60, 65,  1, 13,
       20, 19, 14,  9,  1, 52, 71,  1, 38, 66, 11,  1, 19,  9,  1, 43, 52,
       73, 60, 63, 63, 56,  1, 42, 66, 74,  9,  1, 26, 72, 69, 63, 60, 65,
       58, 71, 66, 65,  0, 31, 52, 69, 55, 56, 65, 70,  9,  1, 71, 59, 56,
        1, 59, 66, 72, 70, 56,  1, 60, 65,  1, 74, 59, 60, 54, 59,  1])

# Creating batches

In [18]:
print(text[:1000])

Chapter I

IN WHICH PHILEAS FOGG AND PASSEPARTOUT ACCEPT EACH OTHER,
THE ONE AS MASTER, THE OTHER AS MAN


Mr. Phileas Fogg lived, in 1872, at No. 7, Saville Row, Burlington
Gardens, the house in which Sheridan died in 1814.  He was one of the
most noticeable members of the Reform Club, though he seemed always to
avoid attracting attention; an enigmatical personage, about whom little
was known, except that he was a polished man of the world.  People said
that he resembled Byron--at least that his head was Byronic; but he was
a bearded, tranquil Byron, who might live on a thousand years without
growing old.

Certainly an Englishman, it was more doubtful whether Phileas Fogg was
a Londoner.  He was never seen on 'Change, nor at the Bank, nor in the
counting-rooms of the "City"; no ships ever came into London docks of
which he was the owner; he had no public employment; he had never been
entered at any of the Inns of Court, either at the Temple, or Lincoln's
Inn, or Gray's Inn; nor had hi

In [0]:
paragraph = '''
Mr. Phileas Fogg lived, in 1872, at No. 7, Saville Row, Burlington
Gardens, the house in which Sheridan died in 1814.  He was one of the
most noticeable members of the Reform Club, though he seemed always to
avoid attracting attention; an enigmatical personage, about whom little
was known, except that he was a polished man of the world.  People said
that he resembled Byron--at least that his head was Byronic; but he was
a bearded, tranquil Byron, who might live on a thousand years without
growing old.
'''

In [20]:
len(paragraph)

508

# training sequences

In [0]:
seq_len = 250

In [0]:
total_seq = len(text)//(seq_len+1) # indexing starts from 0 

In [23]:
print(f'length of sequences in text {total_seq}')

length of sequences in text 1463


In [0]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [25]:
for i in char_dataset.take(500):
    print(ind_to_char[i.numpy()])

C
h
a
p
t
e
r
 
I




I
N
 
W
H
I
C
H
 
P
H
I
L
E
A
S
 
F
O
G
G
 
A
N
D
 
P
A
S
S
E
P
A
R
T
O
U
T
 
A
C
C
E
P
T
 
E
A
C
H
 
O
T
H
E
R
,


T
H
E
 
O
N
E
 
A
S
 
M
A
S
T
E
R
,
 
T
H
E
 
O
T
H
E
R
 
A
S
 
M
A
N






M
r
.
 
P
h
i
l
e
a
s
 
F
o
g
g
 
l
i
v
e
d
,
 
i
n
 
1
8
7
2
,
 
a
t
 
N
o
.
 
7
,
 
S
a
v
i
l
l
e
 
R
o
w
,
 
B
u
r
l
i
n
g
t
o
n


G
a
r
d
e
n
s
,
 
t
h
e
 
h
o
u
s
e
 
i
n
 
w
h
i
c
h
 
S
h
e
r
i
d
a
n
 
d
i
e
d
 
i
n
 
1
8
1
4
.
 
 
H
e
 
w
a
s
 
o
n
e
 
o
f
 
t
h
e


m
o
s
t
 
n
o
t
i
c
e
a
b
l
e
 
m
e
m
b
e
r
s
 
o
f
 
t
h
e
 
R
e
f
o
r
m
 
C
l
u
b
,
 
t
h
o
u
g
h
 
h
e
 
s
e
e
m
e
d
 
a
l
w
a
y
s
 
t
o


a
v
o
i
d
 
a
t
t
r
a
c
t
i
n
g
 
a
t
t
e
n
t
i
o
n
;
 
a
n
 
e
n
i
g
m
a
t
i
c
a
l
 
p
e
r
s
o
n
a
g
e
,
 
a
b
o
u
t
 
w
h
o
m
 
l
i
t
t
l
e


w
a
s
 
k
n
o
w
n
,
 
e
x
c
e
p
t
 
t
h
a
t
 
h
e
 
w
a
s
 
a
 
p
o
l
i
s
h
e
d
 
m
a
n
 
o
f
 
t
h
e
 
w
o
r
l
d
.
 
 
P
e
o
p
l
e
 
s
a
i
d


t
h
a
t
 
h
e
 
r
e
s
e
m
b
l
e
d
 
B
y
r
o
n
-
-
a
t
 
l
e
a
s
t
 
t
h
a
t
 
h
i


In [0]:
sequences = char_dataset.batch(seq_len+1,drop_remainder=True)

In [0]:
def seq_target(seq):
    input_text = seq[:-1]
    target_text = seq[1:]
    return input_text,target_text

In [0]:
dataset = sequences.map(seq_target)

In [29]:
dataset

<MapDataset shapes: ((250,), (250,)), types: (tf.int64, tf.int64)>

In [30]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    print(''.join(ind_to_char[target_txt.numpy()]))

[27 59 52 67 71 56 69  1 33  0  0 33 38  1 47 32 33 27 32  1 40 32 33 36
 29 25 43  1 30 39 31 31  1 25 38 28  1 40 25 43 43 29 40 25 42 44 39 45
 44  1 25 27 27 29 40 44  1 29 25 27 32  1 39 44 32 29 42  9  0 44 32 29
  1 39 38 29  1 25 43  1 37 25 43 44 29 42  9  1 44 32 29  1 39 44 32 29
 42  1 25 43  1 37 25 38  0  0  0 37 69 11  1 40 59 60 63 56 52 70  1 30
 66 58 58  1 63 60 73 56 55  9  1 60 65  1 13 20 19 14  9  1 52 71  1 38
 66 11  1 19  9  1 43 52 73 60 63 63 56  1 42 66 74  9  1 26 72 69 63 60
 65 58 71 66 65  0 31 52 69 55 56 65 70  9  1 71 59 56  1 59 66 72 70 56
  1 60 65  1 74 59 60 54 59  1 43 59 56 69 60 55 52 65  1 55 60 56 55  1
 60 65  1 13 20 13 16 11  1  1 32 56  1 74 52 70  1 66 65 56  1 66 57  1
 71 59 56  0 64 66 70 71  1 65]
Chapter I

IN WHICH PHILEAS FOGG AND PASSEPARTOUT ACCEPT EACH OTHER,
THE ONE AS MASTER, THE OTHER AS MAN


Mr. Phileas Fogg lived, in 1872, at No. 7, Saville Row, Burlington
Gardens, the house in which Sheridan died in 1814.  He was one o

# training batches

In [0]:
batch_size = 128
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

In [32]:
dataset

<BatchDataset shapes: ((128, 250), (128, 250)), types: (tf.int64, tf.int64)>

# Model

In [0]:
vocab_size = len(vocab)
embed_dim = 256
rnn_neurons = 1024

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding,Dropout,GRU
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [0]:
def sparse_cat(y_true,y_pred):
    return sparse_categorical_crossentropy(y_true,y_pred, from_logits=True)

In [36]:
model = Sequential()
model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[batch_size,None]))
model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
model.add(Dense(vocab_size))
model.compile(optimizer='adam',loss=sparse_cat)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 256)          19968     
_________________________________________________________________
gru (GRU)                    (128, None, 1024)         3938304   
_________________________________________________________________
dense (Dense)                (128, None, 78)           79950     
Total params: 4,038,222
Trainable params: 4,038,222
Non-trainable params: 0
_________________________________________________________________


In [37]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")

(128, 250, 78)  <=== (batch_size, sequence_length, vocab_size)


In [38]:
example_batch_predictions

<tf.Tensor: shape=(128, 250, 78), dtype=float32, numpy=
array([[[-1.33452639e-02,  7.75482878e-03, -3.92885972e-03, ...,
          6.38161087e-04,  9.62015940e-04, -8.96746665e-03],
        [-5.09776454e-03,  7.86013203e-04,  9.43000778e-04, ...,
          9.26185865e-04, -1.67493857e-02, -1.33211948e-02],
        [-6.34637335e-03,  6.57085655e-03, -4.64505330e-03, ...,
          1.67192463e-02, -5.60679333e-03,  2.30835611e-03],
        ...,
        [ 7.54932780e-03,  3.76665965e-03, -1.00452062e-02, ...,
         -1.38662066e-02, -5.14511624e-03,  5.95049839e-03],
        [ 1.31298732e-02, -1.24759218e-02, -8.53822194e-03, ...,
         -1.20699853e-02,  1.29118431e-02,  3.68272595e-05],
        [ 1.94363613e-02, -2.26227697e-02, -6.65093819e-03, ...,
         -8.98689311e-03,  1.85874794e-02, -2.94574420e-03]],

       [[-2.20786803e-03,  4.79261577e-03,  3.40996915e-03, ...,
         -1.39263757e-02, -1.81582868e-02, -2.19238224e-03],
        [-5.22776041e-03, -6.47777598e-03,  4.5

In [0]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [40]:
sampled_indices

<tf.Tensor: shape=(250, 1), dtype=int64, numpy=
array([[56],
       [62],
       [65],
       [29],
       [17],
       [ 8],
       [23],
       [71],
       [ 5],
       [63],
       [26],
       [65],
       [ 6],
       [13],
       [64],
       [38],
       [49],
       [44],
       [12],
       [33],
       [35],
       [40],
       [16],
       [59],
       [24],
       [68],
       [44],
       [38],
       [21],
       [ 5],
       [35],
       [13],
       [36],
       [43],
       [49],
       [31],
       [ 8],
       [50],
       [ 1],
       [53],
       [71],
       [57],
       [15],
       [10],
       [33],
       [18],
       [52],
       [22],
       [68],
       [31],
       [25],
       [11],
       [37],
       [ 7],
       [18],
       [ 8],
       [47],
       [65],
       [ 4],
       [65],
       [18],
       [52],
       [66],
       [73],
       [42],
       [40],
       [30],
       [48],
       [15],
       [36],
       [63],
       [14],
       [ 4],
   

In [0]:
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [42]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))

Given the input seq: 

travelling in the
open air, Mr. Fogg proposed to leave her with Passepartout at Fort
Kearney, the servant taking upon himself to escort her to Europe by a
better route and under more favourable conditions.  But Aouda refused
to separate from Mr. Fogg


Next Char Predictions: 

eknE5+;t'lBn(1mNYT0IKP4h?qTN9'K1LSYG+Z btf3-I6a:qGA.M)6+Wn&n6aovRPFX3Ll2&AVUTz
uN9?V?:4I,jf'j
IQb

!Kv2P"NQX2kx08fi?8?22.sDkV
Pom6uvven(9R97;?'7&24eDLqt6EGRnpV)6aBM"'DOv

i;'J,eHteF9BA;&WdWN5
cd9jea:)t"YveCi +5K::6;0Gue5MbjR9-Xgtf2 
mu:pNGbcd0"x7I3N+


In [43]:
model.fit(dataset,epochs=60)

Epoch 1/60
11/11 [==============================] - 2s 213ms/step - loss: 4.3544
Epoch 2/60
11/11 [==============================] - 2s 215ms/step - loss: 3.4614
Epoch 3/60
11/11 [==============================] - 2s 216ms/step - loss: 3.0239
Epoch 4/60
11/11 [==============================] - 2s 218ms/step - loss: 2.8426
Epoch 5/60
11/11 [==============================] - 2s 218ms/step - loss: 2.6788
Epoch 6/60
11/11 [==============================] - 2s 218ms/step - loss: 2.5609
Epoch 7/60
11/11 [==============================] - 2s 220ms/step - loss: 2.4719
Epoch 8/60
11/11 [==============================] - 2s 220ms/step - loss: 2.4118
Epoch 9/60
11/11 [==============================] - 2s 223ms/step - loss: 2.3639
Epoch 10/60
11/11 [==============================] - 2s 222ms/step - loss: 2.3183
Epoch 11/60
11/11 [==============================] - 2s 224ms/step - loss: 2.2787
Epoch 12/60
11/11 [==============================] - 2s 225ms/step - loss: 2.2380
Epoch 13/60
11/11 [======

In [0]:
model.save('/content/drive/My Drive/jv-model.h5')

In [0]:
from tensorflow.keras.models import load_model

In [0]:
model = Sequential()
model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[1,None]))
model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
model.add(Dense(vocab_size))
model.compile(optimizer='adam',loss=sparse_cat)

model.load_weights('/content/drive/My Drive/jv-model.h5')
model.build(tf.TensorShape([1,None]))

In [49]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (1, None, 256)            19968     
_________________________________________________________________
gru_3 (GRU)                  (1, None, 1024)           3938304   
_________________________________________________________________
dense_3 (Dense)              (1, None, 78)             79950     
Total params: 4,038,222
Trainable params: 4,038,222
Non-trainable params: 0
_________________________________________________________________


In [0]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]

  # Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected
 
  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)

      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [52]:
print(generate_text(model,"Aouda",gen_size=500)) #Aouda and  Passepartout are characters from the novel

Aouda. Yow, then, is for from the selvenent of arrest my complements.  As for Passepartout, which he catevers scatce he see off, and
quemed by
a probres by watco followed at the train what owed to him a lear of advirally upon could be
soveres to
men; but there would come in
the since he was by bricks and whirtered like a small.  Aouda had, gonds of gallaged, whither are prudent from impassious.

If the detective e.s not admitiously mutterly graved to
get-followed upon his faces out of Indians,
meridi
