# ASSIGNMENT : IRIS MULTI-CLASS CLASSIFICATION

###### Purpose :
To predict the species of flower .
###### Description :
The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).
###### Requirements :
1) Code must be in tf 2.0 .

2) Accuracy must be in between 95-97% .

3) Model shouldn't be Overfit (You can add drop out layer for this) .

### STEP 1 : Load all the necessary libraries 

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](https://github.com/ramsha275/PIAIC-Sir-Anees-Quarter-2/blob/master/Deep%20Learning/iris.csv),shuffling ,spliting in **Train** and **Test** sets to one-hot-enconding on labels . 


In [2]:
iris = pd.read_csv("iris.csv")
dataset = pd.DataFrame(iris)
dataset.head(15)

sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa

In [3]:
X = dataset.iloc[:,:4].values
y = dataset.iloc[:,4]
#print(y)
encoder = LabelEncoder()
y1 = encoder.fit_transform(y)
#print(y1)
Y = pd.get_dummies(y1).values
print(Y)

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 

In [4]:
#X_t = X[:120]
#Y_t = Y[:120]
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

### STEP 3 : Model Architecture 


###### Input : 4 
###### 1 hidden Layer : 8 nodes
###### Output : 3

In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(8,input_shape=(4,),activation="relu"),
    tf.keras.layers.Dense(3,activation="softmax")
])

In [6]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [7]:
model.fit(X_train,y_train,epochs=200,batch_size=20)

Train on 120 samples
Epoch 1/200
120/120 [==============================] - 1s 10ms/sample - loss: 3.5198 - accuracy: 0.3083
Epoch 2/200
120/120 [==============================] - 0s 133us/sample - loss: 3.2109 - accuracy: 0.3083
Epoch 3/200
120/120 [==============================] - 0s 100us/sample - loss: 2.9245 - accuracy: 0.3167
Epoch 4/200
120/120 [==============================] - 0s 100us/sample - loss: 2.6812 - accuracy: 0.3417
Epoch 5/200
120/120 [==============================] - 0s 133us/sample - loss: 2.5055 - accuracy: 0.4333
Epoch 6/200
120/120 [==============================] - 0s 100us/sample - loss: 2.3784 - accuracy: 0.5500
Epoch 7/200
120/120 [==============================] - 0s 133us/sample - loss: 2.2864 - accuracy: 0.5667
Epoch 8/200
120/120 [==============================] - 0s 133us/sample - loss: 2.2191 - accuracy: 0.5167
Epoch 9/200
120/120 [==============================] - 0s 100us/sample - loss: 2.1544 - accuracy: 0.4667
Epoch 10/200
120/120 [=============

120/120 [==============================] - 0s 100us/sample - loss: 0.6818 - accuracy: 0.8083
Epoch 78/200
120/120 [==============================] - 0s 100us/sample - loss: 0.6757 - accuracy: 0.8083
Epoch 79/200
120/120 [==============================] - 0s 100us/sample - loss: 0.6703 - accuracy: 0.8167
Epoch 80/200
120/120 [==============================] - 0s 100us/sample - loss: 0.6645 - accuracy: 0.8167
Epoch 81/200
120/120 [==============================] - 0s 111us/sample - loss: 0.6585 - accuracy: 0.8333
Epoch 82/200
120/120 [==============================] - 0s 100us/sample - loss: 0.6521 - accuracy: 0.8333
Epoch 83/200
120/120 [==============================] - 0s 100us/sample - loss: 0.6465 - accuracy: 0.8333
Epoch 84/200
120/120 [==============================] - 0s 100us/sample - loss: 0.6406 - accuracy: 0.8250
Epoch 85/200
120/120 [==============================] - 0s 100us/sample - loss: 0.6353 - accuracy: 0.8333
Epoch 86/200
120/120 [==============================] - 0s 

Epoch 154/200
120/120 [==============================] - 0s 100us/sample - loss: 0.3959 - accuracy: 0.9250
Epoch 155/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3940 - accuracy: 0.9250
Epoch 156/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3921 - accuracy: 0.9250
Epoch 157/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3900 - accuracy: 0.9250
Epoch 158/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3883 - accuracy: 0.9250
Epoch 159/200
120/120 [==============================] - 0s 167us/sample - loss: 0.3870 - accuracy: 0.9250
Epoch 160/200
120/120 [==============================] - 0s 200us/sample - loss: 0.3848 - accuracy: 0.9250
Epoch 161/200
120/120 [==============================] - 0s 167us/sample - loss: 0.3827 - accuracy: 0.9417
Epoch 162/200
120/120 [==============================] - 0s 200us/sample - loss: 0.3807 - accuracy: 0.9500
Epoch 163/200
120/120 [==============

### STEP 5 : Evaluation 

In [8]:
evaluation = model.evaluate(X_test,  y_test, verbose=2) 

30/1 - 0s - loss: 0.3371 - accuracy: 0.9667


### STEP 6 : Prediction 

In [9]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
#y_pred_class = np.argmax(y_pred,axis=1)

In [10]:
#y_pred
y_test
#y_test_class

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [11]:
y_test_class

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)